# This is a basic workflow to help you get started with Actions
name: PHP CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install
      run: make install

    - name: Run linter
      run: make lint
